### ISSUE TITLE
Same variable, different binning, 

### ISSUE THREAD

**Issue by seriksen** [FAST-HEP/fast-carpenter#117]
I want to bin the a variable twice, but with different binning in the same dataframe
so in the processing sequence there is
```
dataframe:
    binning:
        - {in: var1, out: name1, bins: {low: -100000, high: 100000, nbins: 200}}
        - {in: var1, out:  name2, bins: {low: -500, high: 500, nbins: 1000}}
```
The resulting csv only uses the binning for `name2`

Current work around is to add a `Define` stage but this won't scale very well.
```
make_more_vars:
    variables:
        - var2: {formula: var1}
            
dataframe:
    binning:
        - {in: var1, bins: {low: -100000, high: 100000, nbins: 200}}
        - {in: var2, bins: {low: -500, high: 500, nbins: 1000}}
```

Could the `BinnedDataframe` stage be adapted to allow for the first approach to work?
