### ISSUE TITLE
Roadmap 0.22.0

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fast-carpenter#145]
With version 0.20.0 almost ready, it is time to plan the next release.

For 0.21.0, the biggest feature will be Multi-tree support (e.g. for CMS L1T and LuxZeplin).
A preview is available in https://github.com/FAST-HEP/fast-carpenter/pull/123.

The only changes from the user perspective are the dataset and processing configs:

```yaml
# data.yml

datasets:
  - eventtype: null
    files:
      # - http://fast-hep-data.web.cern.ch/fast-hep-data/cms/L1T/CMS_L1T_study.root
      - data/CMS_L1T_study.root
    name: test
    nevents:
      "l1CaloTowerEmuTree/L1CaloTowerTree": 1853
      "l1CaloTowerTree/L1CaloTowerTree": 1853
    nfiles: 1
    tree:
      - "l1CaloTowerEmuTree/L1CaloTowerTree"
      - "l1CaloTowerTree/L1CaloTowerTree"
```
&rarr; `nevents` has entries per tree and `tree` allows for lists.

Variables can then be addressed by `<tree name>.<directory>.<tree>.<branch>`:

```yaml
# processing.yml
stages:
    # - diff: "fast_carpenter.Define"
    - var_def: "fast_carpenter.Define"
    - event_selection: 'fast_carpenter.CutFlow'
    - histogram: "fast_carpenter.BinnedDataframe"

var_def:
    variables:
        - nCaloTower: 'l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.nTower'
        - caloEt: l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.iet

event_selection:
    selection:
        All:
            - nCaloTower > 0

diff:
    variables:
        - diff_emu: "l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.iet - l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.et"

histogram:
    binning:
        # - {in: diff_emu, bins: {edges: [-100, -50, -20, 0, 20, 50, 100]}}
        - {in: "nCaloTower", out: nCaloTower, bins: {edges: [0, 1, 5, 10, 20]}}
        - {in: "caloEt", out: caloEt, bins: {edges: [0, 10, 20, 50, 80, 120, 200, 400]}}
```
