### ISSUE TITLE
Simple expressions in binning variable

### ISSUE THREAD

**Issue by rob-tay** [FAST-HEP/fast-carpenter#44]
If you want to bin on a simple transformation of a variable you currently have to create a Define stage which performs the transofrmation. However, for simple things numexpr could called directly on the binning variable, e.g

```yaml
binning:
    - {in: r_cm**2, out: r^2_cm, bins: {low: 2, high: 4733.44, nbins: 100}}
```
Instead of having to add an extra stage,
```yaml
transform:
    variables:
        - r_cm^2: 'r_cm**2'

...

binning:
    - {in: r_cm^2, out: r^2_cm, bins: {low: 2, high: 4733.44, nbins: 100}}
```
