### ISSUE TITLE
Add ability to save pandas dataframe as different file types

### ISSUE THREAD

**Issue by asnaylor** [FAST-HEP/fast-carpenter#53]
Currently `fast_curator` saves the resulting pandas dataframe as a `.csv` file. The user should have option to save the output dataframe in a variety of different file formats.

**Comment by asnaylor** [comment]
I was looking through all the ways to save pandas dataframes on their site and i was wondering do you want to support them all @benkrikler ? https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

**Comment by asnaylor** [comment]
Also my thoughts were having the config yaml file like this:

```
s1logs2:
    binning:
        - {in: singleScatters.s1Area_phd, out: s1}}
    file:
        - {type:".pkl.compress",compression:"gzip"}
```
and support:
```
s1logs2:
    binning:
        - {in: singleScatters.s1Area_phd, out: s1}}
    file:
        - type:".h5"
```

so the user specified the file type and they could also specify other options like compression or etc. that are relevant to saving the pandasframe

**Comment by benkrikler** [comment]
Hey @asnaylor.  

> I was looking through all the ways to save pandas dataframes on their site and i was wondering do you want to support them all @benkrikler ? https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

This is a nice idea and I agree that other outputs are worth considering since you're looking at it now anyway.  For me, the key points for how we implement this sort of change are: 1) backwards compatibility, so existing YAML configs should still work without changes, 2) conciseness for simple cases: if you just want to use hd5 then you shouldn't need to type much else.  Similarly, if you want to save both to cvs and hd5 it shouldn't be hard to do that.  

1. Point 1) means we want to add an option for the config files like you're suggesting, though I'd call it `file_format` or `out_file_format` maybe (just `file` seems a bit ambiguous to me).  
2. Point 2) above means it needs to default to producing csv files.
3. Point 2) above also means we want to support several types of values for this option: a single dictionary with the output file format's config, a list of such dictionaries, possible a single string for simple formats, like csv.

Examples like yours are helpful, so I'm thinking the following values for `file_format` should be allowed:
```yaml
file_format: "csv"
```
```yaml
file_format: {type: ".pkl.compress", compression: "gzip"}
```
```yaml
file_format: 
  - {type: ".pkl.compress", compression: "gzip"}
  - csv
  - type: hdf
    key: df
```
To see how this might be implemented, maybe something like the way we handle binned dataframe weight descriptions could work: https://github.com/FAST-HEP/fast-carpenter/blob/master/fast_carpenter/summary/binning_config.py#L80-L90.

I have a suspicion that this is leaning into a realm where we should really refactor how the outputs are handled in a more general way than just for the binned dataframe stage.   In particular, I'm wondering if this would relate to #52.   But I think we can perhaps put this in now and then refactor it a bit later when we tackle that issue, as the more streamlined way to get there.
