### ISSUE TITLE
BinnedDataframe scribbler does not check for duplicate out variable names

### ISSUE THREAD

**Issue by simonecid** [FAST-HEP/fast-carpenter#92]
Hi, 

By mistake I defined two output variables with the same name in the BinnedDataframe scribbler:
```yaml
DeltaPtOverPtBinner:
 dataset_col: True
 pad_missing: False
 binning:
     - {in: genJetPt, out: genJetPt, bins: {edges:[0, 40, 60, 100]}}
     - {in: caloJetPt, out: genJetPt, bins: {edges:[30, 60, 100]}}
```
And I got a dataframe out of it without any warning. I believe the BinnedDataframe should check for duplicate out variables and give at least a warning when this happens, if not halting the execution with an error.

Simone
